/**
 * Created by Administrator on 2017/9/22.
 */
let jobData = {
      option1:[
        {
          optionName:'未融资',
          check:false,
          type:0,
        },{
          optionName:'天使轮',
          check:false,
          type:0,
        },{
          optionName:'A轮',
          check:false,
          type:0,
        },{
          optionName:'B轮',
          check:false,
          type:0,
        },{
          optionName:'C轮',
          check:false,
          type:0,
        },{
          optionName:'D轮及以上',
          check:false,
          type:0,
        },{
          optionName:'已上市',
          check:false,
          type:0,
        },{
          optionName:'不需要融资',
          check:false,
          type:0,
        }
      ],
      option2:[
      {
        optionName:'0-20人',
        check:false,
        type:1,
      },{
        optionName:'20-99人',
        check:false,
        type:1,
      },{
        optionName:'100-499人',
        check:false,
        type:1,
      },{
        optionName:'500-999人',
        check:false,
        type:1,
      },{
        optionName:'1000-9999人',
        check:false,
        type:1,
      },{
        optionName:'10000人以上',
        check:false,
        type:1,
      }
      ],
      option3:[
      {
        optionName:'非互联网行业',
        check:false,
        type:2,
      },{
        optionName:'健康医疗',
        check:false,
        type:2,
      },{
        optionName:'生活服务',
        check:false,
        type:2,
      },{
        optionName:'旅游',
        check:false,
        type:2,
      },{
        optionName:'金融',
        check:false,
        type:2,
      },{
        optionName:'信息安全',
        check:false,
        type:2,
      },{
        optionName:'广告营销',
        check:false,
        type:2,
      },{
        optionName:'数据服务',
        check:false,
        type:2,
      },{
        optionName:'智能硬件',
        check:false,
        type:2,
      },{
        optionName:'文化娱乐',
        check:false,
        type:2,
      },{
        optionName:'网络招聘',
        check:false,
        type:2,
      },{
        optionName:'分类信息',
        check:false,
        type:2,
      },{
        optionName:'电子商务',
        check:false,
        type:2,
      },{
        optionName:'移动互联网',
        check:false,
        type:2,
      },{
        optionName:'企业服务',
        check:false,
        type:2,
      },{
        optionName:'社交网络',
        check:false,
        type:2,
      },{
        optionName:'教育培训',
        check:false,
        type:2,
      },{
        optionName:'社交网络',
        check:false,
        type:2,
      },{
        optionName:'020',
        check:false,
        type:2,
      },{
        optionName:'游戏',
        check:false,
        type:2,
      },{
        optionName:'互联网',
        check:false,
        type:2,
      },{
        optionName:'互联网',
        check:false,
        type:2,
      },{
        optionName:'媒体',
        check:false,
        type:2,
      },{
        optionName:'IT软件',
        check:false,
        type:2,
      }
  ]
};
let conditionData = {
      option1:[
        {optionName:'中专及以下',
        check:false,
        type:0,},
        {optionName:'高中',
          check:false,
          type:0,},
        {optionName:'大专',
          check:false,
          type:0,},
        {optionName:'本科',
          check:false,
          type:0,},
        {optionName:'硕士',
          check:false,
          type:0,},
        {optionName:'博士',
          check:false,
          type:0,},
      ],
      option2:[
        {optionName:'应届生',
          check:false,
          type:1,},
        {optionName:'1年以内',
          check:false,
          type:1,},
        {optionName:'1-3年',
          check:false,
          type:1,},
        {optionName:'3-5年',
          check:false,
          type:1,},
        {optionName:'5-10年',
          check:false,
          type:1,},
        {optionName:'10年以上',
          check:false,
          type:1,},
      ],
      option3:[
        {optionName:'3K以下',
          check:false,
          type:2,},
        {optionName:'3K-5K',
          check:false,
          type:2,},
        {optionName:'5K-10K',
          check:false,
          type:2,},
        {optionName:'10K-20K',
          check:false,
          type:2,},
        {optionName:'20K-50K',
          check:false,
          type:2,},
        {optionName:'50K以上',
          check:false,
          type:2,},
      ]
}
export  {jobData,conditionData}   /*倒出数据，引入时候使用import {jobData}*/
