<template>
    <div class="location-wrapper">
      <div>

      </div>
    </div>
</template>

<script>
    export default {
        data(){
            return {
                city:{
                    zone:[
                      {
                        zoneName:'南山区',
                        checked:false,
                        children:[
                          {
                            areaName:'全南山区',
                            checked:false,
                          },{
                            areaName:'科技园',
                            checked:false,
                          },{
                            areaName:'大冲',
                            checked:false,
                          },{
                            areaName:'南头',
                            checked:false,
                          },{
                            areaName:'西丽',
                            checked:false,
                          },{
                            areaName:'前海',
                            checked:false,
                          },{
                            areaName:'蛇口',
                            checked:false,
                          },{
                            areaName:'南油',
                            checked:false,
                          },{
                            areaName:'华侨城',
                            checked:false,
                          },{
                            areaName:'后海',
                            checked:false,
                          },{
                            areaName:'深圳湾',
                            checked:false,
                          },{
                            areaName:'海王大厦',
                            checked:false,
                          },{
                            areaName:'海上世界',
                            checked:false,
                          },{
                            areaName:'白石洲',
                            checked:false,
                          },{
                            areaName:'桃源村',
                            checked:false,
                          },{
                            areaName:'新安',
                            checked:false,
                          },{
                            areaName:'翻身路',
                            checked:false,
                          }
                        ]
                      },
                      {
                          zoneName:'宝安区',
                          checked:false,
                          children:[
                            {
                              areaName:'全宝安区',
                              checked:false,
                            },{
                              areaName:'西乡',
                              checked:false,
                            },{
                              areaName:'龙华',
                              checked:false,
                            },{
                              areaName:'民治',
                              checked:false,
                            },{
                              areaName:'新安',
                              checked:false,
                            },{
                              areaName:'福永',
                              checked:false,
                            },{
                              areaName:'沙井',
                              checked:false,
                            },{
                              areaName:'松岗',
                              checked:false,
                            },{
                              areaName:'观澜',
                              checked:false,
                            },{
                              areaName:'翻身路',
                              checked:false,
                            },{
                              areaName:'石岩',
                              checked:false,
                            },{
                              areaName:'桃源居',
                              checked:false,
                            },{
                              areaName:'光明',
                              checked:false,
                            },{
                              areaName:'滢水山庄',
                              checked:false,
                            },{
                              areaName:'锦绣江南',
                              checked:false,
                            },{
                              areaName:'坂田',
                              checked:false,
                            },{
                              areaName:'西丽',
                              checked:false,
                            },{
                              areaName:'南头',
                              checked:false,
                            },{
                              areaName:'平湖',
                              checked:false,
                            }
                          ]

                      },
                      {
                        zoneName:'福田区',
                        checked:false,
                        children:[
                          {
                            areaName:'全福田区',
                            checked:false,
                          },{
                            areaName:'车公庙',
                            checked:false,
                          },{
                            areaName:'上步',
                            checked:false,
                          },{
                            areaName:'岗厦',
                            checked:false,
                          },{
                            areaName:'梅林',
                            checked:false,
                          },{
                            areaName:'皇岗',
                            checked:false,
                          },{
                            areaName:'益田村',
                            checked:false,
                          },{
                            areaName:'购物公园',
                            checked:false,
                          },{
                            areaName:'香蜜湖',
                            checked:false,
                          },{
                            areaName:'沙头',
                            checked:false,
                          },{
                            areaName:'石厦',
                            checked:false,
                          },{
                            areaName:'八卦岭',
                            checked:false,
                          },{
                            areaName:'华强北',
                            checked:false,
                          },{
                            areaName:'上梅林',
                            checked:false,
                          },{
                            areaName:'景田',
                            checked:false,
                          },{
                            areaName:'组织另',
                            checked:false,
                          },{
                            areaName:'新洲',
                            checked:false,
                          },{
                            areaName:'园岭',
                            checked:false,
                          },{
                            areaName:'下沙',
                            checked:false,
                          },{
                            areaName:'赤尾',
                            checked:false,
                          },{
                            areaName:'莲花二村',
                            checked:false,
                          },{
                            areaName:'振华路',
                            checked:false,
                          },{
                            areaName:'下梅林',
                            checked:false,
                          },{
                            areaName:'笔架山',
                            checked:false,
                          },{
                            areaName:'莲花北村',
                            checked:false,
                          },{
                            areaName:'沙尾',
                            checked:false,
                          },{
                            areaName:'泥岗',
                            checked:false,
                          },{
                            areaName:'蔡屋围',
                            checked:false,
                          },{
                            areaName:'沙嘴',
                            checked:false,
                          },{
                            areaName:'上沙',
                            checked:false,
                          },{
                            areaName:'华侨城',
                            checked:false,
                          },{
                            areaName:'莲花一村',
                            checked:false,
                          },{
                            areaName:'东门',
                            checked:false,
                          },{
                            areaName:'笋岗',
                            checked:false,
                          },{
                            areaName:'银湖',
                            checked:false,
                          }
                        ]
                      },
                      {
                        zoneName:'龙岗区',
                        checked:false,
                        children:[
                          {
                            areaName:'全龙岗区',
                            checked:false,
                          },{
                            areaName:'坂田',
                            checked:false,
                          },{
                            areaName:'平湖',
                            checked:false,
                          },{
                            areaName:'横岗',
                            checked:false,
                          },{
                            areaName:'布吉',
                            checked:false,
                          },{
                            areaName:'滢水山庄',
                            checked:false,
                          },{
                            areaName:'坪地',
                            checked:false,
                          },{
                            areaName:'坪山',
                            checked:false,
                          },{
                            areaName:'大芬村',
                            checked:false,
                          },{
                            areaName:'万科城',
                            checked:false,
                          },{
                            areaName:'康桥',
                            checked:false,
                          },{
                            areaName:'桂芳园',
                            checked:false,
                          },{
                            areaName:'草铺',
                            checked:false,
                          },{
                            areaName:'民治',
                            checked:false,
                          },{
                            areaName:'葵涌',
                            checked:false,
                          },{
                            areaName:'观澜',
                            checked:false,
                          },{
                            areaName:'龙华',
                            checked:false,
                          },{
                            areaName:'布心',
                            checked:false,
                          }
                        ]
                      },
                      {
                        zoneName:'罗湖区',
                        checked:false,
                        children:[
                          {
                            areaName:'全罗湖区',
                            checked:false,
                          },{
                            areaName:'东门',
                            checked:false,
                          },{
                            areaName:'火车站',
                            checked:false,
                          },{
                            areaName:'笋岗',
                            checked:false,
                          },{
                            areaName:'国贸',
                            checked:false,
                          },{
                            areaName:'莲塘',
                            checked:false,
                          },{
                            areaName:'蔡屋围',
                            checked:false,
                          },{
                            areaName:'田贝',
                            checked:false,
                          },{
                            areaName:'翠竹',
                            checked:false,
                          },{
                            areaName:'黄贝岭',
                            checked:false,
                          },{
                            areaName:'水贝',
                            checked:false,
                          },{
                            areaName:'东湖',
                            checked:false,
                          },{
                            areaName:'人民南',
                            checked:false,
                          },{
                            areaName:'文锦渡',
                            checked:false,
                          },{
                            areaName:'布心',
                            checked:false,
                          },{
                            areaName:'泥岗',
                            checked:false,
                          },{
                            areaName:'清水河',
                            checked:false,
                          },{
                            areaName:'草铺',
                            checked:false,
                          },{
                            areaName:'洪湖',
                            checked:false,
                          },{
                            areaName:'圆岭',
                            checked:false,
                          },{
                            areaName:'布吉',
                            checked:false,
                          },{
                            areaName:'东晓',
                            checked:false,
                          },{
                            areaName:'水库',
                            checked:false,
                          },{
                            areaName:'银湖',
                            checked:false,
                          },{
                            areaName:'八卦岭',
                            checked:false,
                          }
                        ]
                      },
                      {
                        zoneName:'龙华区',
                        checked:false,
                        children:[
                          {
                            areaName:'全龙华区',
                            checked:false,
                          },{
                            areaName:'龙华',
                            checked:false,
                          },{
                            areaName:'民治',
                            checked:false,
                          },{
                            areaName:'观澜',
                            checked:false,
                          },{
                            areaName:'锦绣江南',
                            checked:false,
                          },{
                            areaName:'滢水山庄',
                            checked:false,
                          },{
                            areaName:'坂田',
                            checked:false,
                          },{
                            areaName:'平湖',
                            checked:false,
                          },{
                            areaName:'山岩',
                            checked:false,
                          }
                        ]
                      },
                      {
                        zoneName:'盐田区',
                        checked:false,
                        children:[
                          {
                            areaName:'全盐田区',
                            checked:false,
                          },{
                            areaName:'沙头角',
                            checked:false,
                          },{
                            areaName:'大梅沙',
                            checked:false,
                          },{
                            areaName:'小梅沙',
                            checked:false,
                          }
                        ]
                      },
                      {
                        zoneName:'坪山区',
                        checked:false,
                        children:[
                          {
                            areaName:'全坪山区',
                            checked:false,
                          },{
                            areaName:'坪山',
                            checked:false,
                          }
                        ]

                      }
                    ],
                    subwayLine:[

                    ]
                }
            }
        }



    }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>
